### ISSUE TITLE
init 就报错

### ISSUE THREAD

**Issue by bolan9999** [louis-tru/ngui#1]
我没有使用npm安装，因为npm太慢了，使用的yarn全局安装，但是安装好了执行ngui init报如下错误

fs.js:953
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/Stone/.config/yarn/global/node_modules/ngui-tools/product/node_modules/ngui'
    at Object.fs.statSync (fs.js:953:11)
    at Object.exports.cp_sync (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/fs.js:470:17)
    at /Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:682:14
    at Array.forEach (native)
    at constructor.initialize (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:679:23)
    at Object.<anonymous> (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/bin/shell.js:51:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

**Comment by chuxuewen** [comment]
应该是这个  `/Users/Stone/.config/yarn/global/node_modules/ngui-tools/product/node_modules/ngui` 这个node包不存在，这个是必须的，可能是由于  父目录`node_modules
 ` 导致安装忽略了这个包。

On Dec 5, 2017, at 10:18 PM, bolan9999 <notifications@github.com<mailto:notifications@github.com>> wrote:


我没有使用npm安装，因为npm太慢了，使用的yarn全局安装，但是安装好了执行ngui init报如下错误

fs.js:953
binding.stat(pathModule._makeLong(path));
^

Error: ENOENT: no such file or directory, stat '/Users/Stone/.config/yarn/global/node_modules/ngui-tools/product/node_modules/ngui'
at Object.fs.statSync (fs.js:953:11)
at Object.exports.cp_sync (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/fs.js:470:17)
at /Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:682:14
at Array.forEach (native)
at constructor.initialize (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:679:23)
at Object. (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/bin/shell.js:51:9)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)

**Comment by louis-tru** [comment]
我一会上传新包，把这个目录名称改一下。

On Dec 5, 2017, at 10:25 PM, chuxuewen <notifications@github.com<mailto:notifications@github.com>> wrote:

应该是这个 `/Users/Stone/.config/yarn/global/node_modules/ngui-tools/product/node_modules/ngui` 这个node包不存在，这个是必须的，可能是由于 父目录`node_modules
` 导致安装忽略了这个包。

On Dec 5, 2017, at 10:18 PM, bolan9999 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


我没有使用npm安装，因为npm太慢了，使用的yarn全局安装，但是安装好了执行ngui init报如下错误

fs.js:953
binding.stat(pathModule._makeLong(path));
^

Error: ENOENT: no such file or directory, stat '/Users/Stone/.config/yarn/global/node_modules/ngui-tools/product/node_modules/ngui'
at Object.fs.statSync (fs.js:953:11)
at Object.exports.cp_sync (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/fs.js:470:17)
at /Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:682:14
at Array.forEach (native)
at constructor.initialize (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/build.js:679:23)
at Object. (/Users/Stone/.config/yarn/global/node_modules/ngui-tools/bin/shell.js:51:9)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)

**Comment by louis-tru** [comment]
新包已经上传，你可以去试试
